# Generated by Django 6.0.3 on 2026-06-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', 'XXXX_add_tarifa_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifa',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
